{% set name = "cement" %}
{% set version = "3.0.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c4a7c6c644edb06d0a9d4fe246c9be06b0ba713a283e9288a6c4676c3e0c15b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cement = cement.cli.main:main


requirements:
  host:
    - python >=3.6
    - pip
    - pdm
    - pdm-backend 

  run:
    - python >=3.6

test:
  imports:
    - cement
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://builtoncement.com
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: CLI Application Framework for Python
  doc_url: http://builtoncement.com/2.6/
  dev_url: https://github.com/datafolklabs/cement

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
