{% set name = "cement" %}
{% set version = "3.0.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73d1015ebf9b8df13e6bc987edf0d4be3f1c8b4438921eea8d66cbb5504aee15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cement = cement.cli.main:main


requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - cement
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://builtoncement.com
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: CLI Application Framework for Python
  doc_url: http://builtoncement.com/2.6/
  dev_url: https://github.com/datafolklabs/cement

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
