appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ehQAyEI2hZF1rdnDHZ5MdsJyIdU3kxGKxSK7aTu/eGeFj9COYL/it9R5BustvMT9C/Nlj0GafQtRwTq/pnpnVhPfAb2XEW7RYTBNYRgA9fzzDiq4Xj1HOPkne0J5R4T58cwo7uRWWOynNEdTRAiBCFWRtiociU+yppHQkagm2luGPHusPQppmKZLNCCvhz+M9kKIVW8Qt4EgVGItMdEgxTCpml2SBttSRR0pmUGnOR9vE9FE+gO93YpVhOw6iAwT4dkm/5znXnM8I7Ffv4ssejfTRrgEhvlulcpI+ssQDeDH4sYuaXRsn51aaF3w8VoVwaDNjWai1hJYPcpCAvHYcQkFYMqNKQ7xARi9fMf24j+OrdcEvzs5GFPgdyTzqMSZWm7ElUAP6Q7zHtPHTszza/6c1S9PV/MKomH6ZbHbBsJeGiTRdLC7pJ1E3l9YWhPK+wbKHXq/LtF4aw14lHukLID9dbWJcdXOP9xbL1+EvmQWsGOrdt/CxtDsc1lvczkYHU8mWnrrMIsjft5CZmxaziI/SkapIXjxGl/6OQGQPdPG7QoZ9gTpuNnefRKoWtMqQuY0LPduY66cNDLb8bSwi/oDTK8WWyA/QE/toca42WPfPWScRSJZRsHId/x/uvejHU2h4MQbI7LitzoAXlw5Tiooq3OVuAcJ1jWw3YK3FJM=}
